stages:
   data_ingestion:
     cmd : python src/data_ingestion.py
     deps:
        - src/data_ingestion.py 
        - data/raw


   data_Preprocessing:
     cmd : python src/data_preprocessing.py
     deps:
        - src/data_preprocessing.py 
        


   feature_engineering:
     cmd : python src/feature_engineering.py
     deps:
        - src/feature_engineering.py 
        


   model_building:
     cmd : python src/model_building.py
     deps: 
        - src/model_building.py
        - src/data_ingestion.py
        - src/data_preprocessing.py
        - src/feature_engineering.py
        - data/raw/creditcard.csv
     outs: 
        - model.pkl


   model_evaluation:
     cmd : python src/model_evaluation.py
     deps:
        - src/model_evaluation.py 
        - model.pkl
     metrics:
        - metrics.json
        
